apps/accounts/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from . forms import RegisterForm, LoginForm, OtpVerificationForm, PasswordResetRequestForm, PasswordResetForm
from . models import User, Timezone
from flask_login import login_user, logout_user
from . decorators import login_required, logout_required
from setup.extensions import login_manager, db
from . senders import Util
from . tokens import Token

accounts_router = Blueprint('accounts_router', __name__, template_folder="templates")

@accounts_router.route('/register', methods=['GET', 'POST'])
@logout_required
def register():
    form = RegisterForm(request.form)
    timezones = Timezone.query.all()
    timezones_list=[(t.name, t.name) for t in timezones]
    form.tz.choices = timezones_list
    if form.validate_on_submit():
        user = User.create_user(
            name=form.name.data,
            email=form.email.data.lower(),
            phone=form.phone.data,
            tz=form.tz.data,
            password=form.password.data,
            terms_agreement=form.terms_agreement.data,
        )
        Util.send_verification_email(request, user)
        return render_template('accounts/email-activation-request.html', detail='sent', email=user.email)
    return render_template('accounts/register.html', form=form)

@accounts_router.route('/activate-user/<token>/<user_id>/', methods=['GET'])
@logout_required
def activate_user(token, user_id):
    user_obj = User.query.filter_by(id=user_id).first()
    if not user_obj:
        flash("You entered an invalid link!", {"heading": "Invalid", "tag": "error"})
        return redirect(url_for("accounts_router.login"))
    user = Token.verify_activation_token(token)
    if not user:
        return render_template('accounts/email-activation-failed.html', email=user_obj.email)
    if user.id != user_obj.id:
        flash("You entered an invalid link!", {"heading": "Invalid", "tag": "error"})
        return redirect(url_for("accounts_router.login"))

    user.current_activation_jwt['used'] = True
    user.is_email_verified = True
    db.session.commit()

    if not user.is_phone_verified:
        Util.send_sms_otp(user)
        session['verification_phone'] = user.phone
        flash("Activation successful!. Verify your phone now!", {"heading": "Done", "tag": "success"})
        return redirect(url_for('accounts_router.verify_otp'))

    flash("Activation successful!.", {"heading": "Done", "tag": "success"})
    Util.send_welcome_email(request, user)
    return redirect(url_for("accounts_router.login"))

@accounts_router.route('/resend-activation-email/', methods=['GET'])
@logout_required
def resend_activation_email():
    email = request.cookies.get('activation_email')
    user_obj = User.query.filter_by(email=email).first()
    if not user_obj:
        flash("Something went wrong!.", {"heading": "error", "tag": "error"})
        return redirect(url_for("accounts_router.login"))
    if user_obj.is_email_verified:
        flash("Your email address has already been verified!.", {"heading": "Verified", "tag": "info"})
        return redirect(url_for("accounts_router.login"))

    Util.send_verification_email(request, user_obj)
    return render_template('accounts/email-activation-request.html', detail='resent', email=email)

@accounts_router.route('/verify-otp', methods=['GET', 'POST'])
@logout_required
def verify_otp():
    phone = session.get('verification_phone')
    if not phone:
        flash("Back to login!.", {"heading": "Error!", "tag": "error"})
        return redirect(url_for('accounts_router.login'))
    form = OtpVerificationForm(request.form)
    if form.validate_on_submit():
        flash("You can login now.", {"heading": "Verification complete!", "tag": "success"})
        return redirect(url_for('accounts_router.login'))
    return render_template('accounts/otp-verification.html', form=form)

@accounts_router.route('/resend-otp', methods=['GET'])
@logout_required
def resend_otp():
    phone = session.get('verification_phone')
    if not phone:
        flash("Something went wrong.", {"heading": "Error!", "tag": "info"})
        return redirect(url_for('accounts_router.login'))
    user = User.query.filter_by(phone=phone).first()
    if not user:
        flash("Invalid user.", {"heading": "Error!", "tag": "error"})
        return redirect(url_for('accounts_router.login'))
    if user.is_phone_verified:
        flash("Your phone number has already been verified.", {"heading": "Already verified!", "tag": "info"})
        return redirect(url_for('accounts_router.login'))
    
    Util.send_sms_otp(user)
    flash("A new otp has been sent to your phone number.", {"heading": "Sent!", "tag": "success"})
    return redirect(url_for('accounts_router.verify_otp'))


@accounts_router.route('/login', methods=['GET', 'POST'])
@logout_required
def login():
    session['password_reset_email'] = None
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email_or_phone.data).first() or User.query.filter_by(phone=form.email_or_phone.data).first()
        if not user:
            flash("Invalid credentials.", {"heading": "Error!", "tag": "error"})
            return redirect(url_for('accounts_router.login'))
        password_check = user.check_password(form.password.data)
        if password_check == False:
            flash("Invalid credentials.", {"heading": "Error!", "tag": "error"})
            return redirect(url_for('accounts_router.login')) 

        if not user.is_email_verified:
            Util.send_verification_email(request, user)
            return render_template('accounts/email-activation-request.html', detail='request', email=user.email)

        if not user.is_phone_verified:
            Util.send_sms_otp(user)
            session['verification_phone'] = user.phone
            return redirect(url_for('accounts_router.verify_otp'))
        login_user(user)
        return redirect(url_for("chat_router.home"))
    return render_template('accounts/login.html', form=form)

@accounts_router.route('/logout', methods=['GET'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('accounts_router.login'))

@accounts_router.route('/request-password-reset', methods=['GET', 'POST'])
@logout_required
def password_reset_request():
    detail = 'first_view'
    form = PasswordResetRequestForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            Util.send_password_reset_email(request, user)
            session['password_reset_email'] = user.email
            detail = 'second_view'
    return render_template('accounts/password-reset-request.html', detail=detail, form=form)

@accounts_router.route('/verify-password-reset-token/<token>/<user_id>', methods=['GET', 'POST'])
@logout_required
def verify_password_reset_token(token, user_id):
    detail = 'invalid_token'
    form = None
    try:
        user_obj = User.query.filter_by(id=user_id).first()
    except:
        flash("You entered an invalid link.", {"heading": "Error!", "tag": "error"})
        return redirect(url_for("accounts_router.login"))
    user = Token.verify_reset_token(token)
    
    if user and user.id != user_obj.id:
        flash("You entered an invalid link.", {"heading": "Error!", "tag": "error"})
        return redirect(url_for("accounts_router.login"))
    elif user and user.id == user_obj.id:
        session['password_reset_email'] = user_obj.email
        return redirect(url_for('accounts_router.reset_password'))
    return render_template('accounts/password-reset.html', detail=detail, form=form, email=user_obj.email)

@accounts_router.route('/reset-password', methods=['GET', 'POST'])
@logout_required
def reset_password():
    email=session.get('password_reset_email')
    user = User.query.filter_by(email=email).first()
    if not user:
        flash("Not allowed.", {"heading": "Error!", "tag": "error"})
        return redirect(url_for('accounts_router.login'))
    detail = 'valid_token'
    form = PasswordResetForm(request.form)
    if form.validate_on_submit():
        if user:
            user.password = form.newpassword.data
            db.session.commit()
            flash("Your password has been reset.", {"heading": "Success!", "tag": "success"})
            session['password_reset_email'] = None
            return redirect(url_for("accounts_router.login"))
    return render_template('accounts/password-reset.html', detail=detail, form=form, email=email)

@accounts_router.route('/resend-password-token/<email>', methods=['GET'])
@logout_required
def resend_password_token(email):
    detail = 'third_view'
    user = User.query.filter_by(email=email).first()
    if not user:
        flash("Something went wrong.", {"heading": "Error!", "tag": "error"})
        return redirect(url_for("accounts_router.login"))
    
    Util.send_password_reset_email(request, user)
    return render_template('accounts/password-reset-request.html', detail=detail, form=None)

@login_manager.user_loader
def load_user(user_id):
    return User.query.filter_by(id=user_id).first()

apps/accounts/templates/accounts/email-activation-failed.html
{% extends "accounts/index.html" %}
{% block title %}Email Activation Failed{% endblock %}
{% block content %}
	<h1 style="font-weight: bold;">WWC V4 EMAIL ACTIVATION FAILED</h1>
	<div class="main-agileinfo">
		<div class="agileits-top">
			<div>
				<p>Sorry! This link has already been used or expired!</p>
				<input class="resend-email" onclick="window.location=`{{ url_for('accounts_router.resend_activation_email') }}`" type="submit" value="RESEND ACTIVATION EMAIL">
            </div>
		</div>
	</div>
{% endblock %}

{% block js %}
	<script>
		document.cookie = 'activation_email=' + '{{email}}' + ";domain=;path=/"
	</script>
{% endblock %}

apps/accounts/templates/accounts/email-activation-request.html
{% extends "accounts/index.html" %}
{% block title %}
{% if detail == 'request' %}
Unverified Email Address
{% else %}
Email Activation Sent
{% endif %}
{% endblock %}
{% block content %}
	<h1 style="font-weight: bold;">WWC V4 {% if detail == 'request' %}UNVERIFIED EMAIL ADDRESS {% else %}EMAIL ACTIVATION SENT {% endif %}</h1>
	<div class="main-agileinfo">
		<div class="agileits-top">
			<div>
				{% if detail == 'request' %}
					<p>Your email address is yet to be verified. Check your email or click below to resend activation link</p>
				{% else %}
					<p>Check your email for {% if detail == 'resent' %}new {% endif %}activation link!</p>
				{% endif %}
				<input class="resend-email" onclick="window.location=`{{ url_for('accounts_router.resend_activation_email') }}`" type="submit" value="RESEND ACTIVATION EMAIL">
			</div>
		</div>
	</div>
{% endblock %}

{% block js %}
	<script>
		document.cookie = 'activation_email=' + '{{email}}' + ";domain=;path=/"
	</script>
{% endblock %}

apps/accounts/templates/accounts/index.html
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
<title>Whatsapp Web Clone V1 | {% block title %}{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- Custom Theme files -->
<link href="{{ url_for('static', filename = 'css/register.css') }}" rel="stylesheet" type="text/css" media="all" />
<link rel="shortcut icon" href="{{ url_for('static', filename = 'media/whatsapp.png') }}" type="image/x-icon">

<!-- //Custom Theme files -->
<!-- web font -->
<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
<!-- //web font -->
<!--Sweet alert-->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10.10.1/dist/sweetalert2.min.css">
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.10.1/dist/sweetalert2.all.min.js"></script>

<style>
	.register-form p, .login-form p:not(:last-child){
		display: inline-block;
		font-weight: bold; 
		font-size: 11px; 
		color: gold; 
		margin-bottom:2em ;
		
	}
	
	@media(max-width:600px){
		.register-form p{
			margin-bottom:1.5em ;
		}	
	}
</style>
</head>
<body>
	{% with messages = get_flashed_messages(with_categories=true) %}
	{% if messages %}
	{% for category, message in messages %}
	<script>
	   
	   Swal.fire({
 
		title: "{{ category.heading.title() }}",
		// success , error , warning ,info

		text: "{{ message }}",
		// Custom message flashed from your flask routes

		icon:"{{ category.tag }}",
		// success , error , warning ,info
		timer: 3500

	   })
 
	</script>
	{% endfor %}
	{% endif %}
	{% endwith %}
	<!-- main -->
	<div class="main-w3layouts wrapper">
        {% block content %}
        {% endblock %}
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p id="copyright-date"></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
	<script src="{{ url_for('static', filename = 'vendors/js/jquery-3.6.1.min.js') }}"></script>
	<script>
		window.onload = function() {
			var year = new Date().getFullYear()
			document.getElementById('copyright-date').innerHTML = `© ${year} Whatsapp Web Clone V4. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a>`
		}
		$.ajaxSetup({
			headers: {"X-CSRFToken": '{{csrf_token}}'}
		})

		/* Sweetify Toast Config */
		const Toast = Swal.mixin({
            toast: true,
            position: 'top-right',
            iconColor: 'white',
            customClass: {
                popup: 'colored-toast'
            },
            showConfirmButton: false,
            timer: 2000,
            timerProgressBar: true
        })
    </script>
    {% block js %}
    {% endblock %}
</body>
</html>

apps/accounts/templates/accounts/login.html
{% extends "accounts/index.html" %}
{% block title %}Register{% endblock %}
{% block content %}
	<h1 style="font-weight: bold;">WWC V4 LOGIN FORM</h1>
	<div class="main-agileinfo">
		<div class="agileits-top">
			<form method="post" class="login-form">
				{{ form.csrf_token }}
				{{form.email_or_phone(placeholder="Email or Phone")}}
				<p class="error"></p>
				{{form.password(placeholder="Password")}}
				<p class="error"></p>

				<div class="wthree-text" >
				<input id="submit-btn" type="submit" value="LOGIN">
			</form>
			<p>
				Don't have an Account? <a href="{{ url_for('accounts_router.register') }}"> Register Now!</a>
				<br>Forgot Password? <a href="{{ url_for('accounts_router.password_reset_request') }}">Click Here</a>
			</p>
			
		</div>
	</div>
{% endblock %}

apps/accounts/templates/accounts/otp-verification.html
{% extends "accounts/index.html" %}
{% block title %}Verify Phone Number{% endblock %}
{% block content %}
	<h1 style="font-weight: bold;">WWC V1 VERIFY PHONE NUMBER</h1>
	<div class="main-agileinfo">
		<div class="agileits-top">
			<p style="font-weight: bold; margin-bottom: 10px;">Complete verification by entering the 6 digit <br>code sent to your phone number!</p>
			<form method="post" class="register-form">
				{{ form.csrf_token }}
				{{form.otp(placeholder="Enter Otp")}}
				{% for error in form.otp.errors %}<p>{{error}}</p>{% endfor %}
				<input type="submit" value="SUBMIT">
			</form>
			<p>Didn't get an OTP? <a style="cursor: pointer;" href="{{url_for('accounts_router.resend_otp')}}" class="resend-otp"> Resend OTP!</a></p>
		</div>
	</div>
{% endblock %}

apps/accounts/templates/accounts/password-reset-request.html
{% extends "accounts/index.html" %}
{% block title %}
	{% if detail == 'second_view' %}
		Email Sent
	{% elif detail == 'third_view' %}
		Email Resent
	{% else %}
		Request Reset Password
	{% endif %}
{% endblock %}
{% block content %}
	{% if detail == 'first_view' %}
	<h1 style="font-weight: bold;">REQUEST RESET PASSWORD</h1>
	<div class="main-agileinfo">
		<div class="agileits-top">
            <p style="font-weight: bold; margin-bottom: 10px;">Forgotten your password? <br>Enter your email address below and we'll email instructions for setting a new one.</p>
			<form method="post" class="login-form">
				{{ form.csrf_token }}
				{{form.email(placeholder="Enter your email address")}}
				{% for e in form.email.errors %}<p>{{e}}</p>{% endfor %}

				<div class="wthree-text" >
				<input type="submit" value="SEND EMAIL">
			</form>
			<p><a href="{{ url_for('accounts_router.login') }}"> Back to Login!</a></p>
		</div>
	</div>
	{% elif detail == 'second_view' %}
	<h1 style="font-weight: bold;">EMAIL SENT</h1>
	<div class="main-agileinfo">
		<div class="agileits-top">
            <p style="font-weight: bold; margin-bottom: 10px;">We've emailed you with instructions for resettng your password. If an account exists with the email you entered, you should receive it shortly</p>
            <p style="font-weight: bold; margin-bottom: 10px;">If you didn't receive an email, make sure you've entered the email address you registered with, and check your spam folder.</p>

			<p><a href="{{ url_for('accounts_router.login') }}"> Back to Login!</a></p>
		</div>
	</div>
	{% else %}
	<h1 style="font-weight: bold;">EMAIL RESENT</h1>
	<div class="main-agileinfo">
		<div class="agileits-top">
            <p style="font-weight: bold; margin-bottom: 10px;">We've resent the instructions for resettng your password.</p>
            <!-- <p style="font-weight: bold; margin-bottom: 10px;">If you didn't receive an email, make sure you've entered the email address you registered with, and check your spam folder.</p> -->

			<p><a href="{{ url_for('accounts_router.login') }}"> Back to Login!</a></p>
		</div>
	</div>
	{% endif %}
{% endblock %}

apps/accounts/templates/accounts/password-reset.html
{% extends "accounts/index.html" %}
{% block title %}
	{% if detail == 'invalid_token' %}
		Broken Link
	{% else %}
		Reset Password Form
	{% endif %}
{% endblock %}
{% block content %}
    <style>
        li{
            color: gold;
            font-size: 12px;
            font-weight: bold;
            margin-top: 10px;
        }
    </style>
	{% if detail == 'valid_token' %}
	<h1 style="font-weight: bold;">RESET PASSWORD FORM</h1>
	<div class="main-agileinfo">
		<div class="agileits-top">
            <p style="font-weight: bold; margin-bottom: 10px;">Please enter your new password twice so we can verify you typed it in correctly.</p>
			<form method="post" class="login-form">
				{{ form.csrf_token }}
				{{ form.newpassword(placeholder="New password") }}
				{% for e in form.newpassword.errors %}<p>{{e}}</p>{% else %}<p></p>{% endfor %}
				{{ form.confirm(placeholder="Confirm password") }}
				{% for e in form.confirm.errors %}<p>{{e}}</p>{% endfor %}

				<div class="wthree-text" >
				<input type="submit" value="UPDATE PASSWORD">
			</form>
			<p><a href="{{ url_for('accounts_router.login') }}"> Back to Login!</a></p>
		
		</div>
	</div>
	{% else %}
	<h1 style="font-weight: bold;">WWC V4 BROKEN LINK</h1>
	<div class="main-agileinfo">
		<div class="agileits-top">
			<div>
				<p>Sorry! This link has already been used or expired!</p>
				<input class="resend-email" onclick="window.location=`{{ url_for('accounts_router.resend_password_token', email=email) }}`" type="submit" value="RESEND PASSWORD RESET EMAIL">
            </div>
		</div>
	</div>
	{% endif %}
{% endblock %}

apps/accounts/templates/accounts/register.html
{% extends "accounts/index.html" %}
{% block title %}Register{% endblock %}
{% block content %}
	<h1 style="font-weight: bold;">WWC V4 SIGNUP FORM</h1>
	<div class="main-agileinfo">
		<div class="agileits-top">
			<form method="post" class="register-form">
				{% for field in form if not field.name == 'terms_agreement' %}
					{{field}}
					{% for error in field.errors  %}
						<p style="text-align: left; margin-top: 5px;">{{error}}</p>
					{% else %}
						<p></p>
					{% endfor %}
				{% endfor %}
				

				<div class="wthree-text" >
					<label class="anim">
						{{form.terms_agreement(class="checkbox")}}
						<span>I Agree To The Terms & Conditions</span>
					</label>
					<div class="clear"> </div>
				</div>
				<input id="submit-btn" type="submit" value="SIGNUP">
			</form>
			<p>Already have an Account? <a href="{{url_for('accounts_router.login')}}"> Login Now!</a></p>
		</div>
	</div>
{% endblock %}

{% block js %}
	<script type="text/javascript">
		var localtz = Intl.DateTimeFormat().resolvedOptions().timeZone // Get local timezone
		var select_element = document.getElementById('tz') // Get select element
		var options = Array.from(document.querySelectorAll('option')); 
		try{
			var optionMatch = options.find(el => {
				return el.textContent == localtz;
			});

			select_element.value = optionMatch.value
		}catch{
			select_element.value = ''   
		}
    </script>
{% endblock %}